### ISSUE TITLE
IllIllI - Reward distribution assumes funds are dispersed even if there are no recipients

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-truflation-judging#126]
IllIllI

medium

# Reward distribution assumes funds are dispersed even if there are no recipients

## Summary

The `VirtualStakingRewards`'s accounting logic does not properly handle cases where time passes without any staked users.

## Vulnerability Detail

The contract keep track of the total time passed, as well as the cumulative rate of rewards that have been generated, so that for every user, it just has to keep track of the last timestamp and last rate at the time of the last withdrawal, in order to calculate the rewards owed since the user began staking. The code special-cases the scenario where there are no users, by not updating the cumulative rate when the `_totalSupply` is zero, but it does not include such a condition for the tracking of the timestamp. Because of this, even when there are no users staking, the accounting logic still thinks funds were being dispersed during that timeframe (because the starting timestamp is updated), which means the funds effectively are distributed to nobody, rather than being saved for when there is someone to receive them.

## Impact

If funds are added and `notifyRewardAmount()` is called prior to there being any users staking (as is done in the [deployment script](https://github.com/sherlock-audit/2023-12-truflation/blob/main/truflation-contracts/script/01_deployTrufAndVesting.sol#L35-L37)), the funds that should have gone to the first stakers will instead accrue to nobody.

The funds are not locked in the contract forever though, because the admin can call `notifyRewardAmount()` without transferring any extra funds, which will use the latent balance as the reward source. However, the set of people and their durations will not be the same as the set in existence when the first notification happened.

In this POC, Alice doesn't stake until three days after the first reward notification, and therefore the first three days of rewards get stuck in the contract. After the [default](https://github.com/sherlock-audit/2023-12-truflation/blob/main/truflation-contracts/src/staking/VirtualStakingRewards.sol#L27) 7-day duration, the admin calls `notifyRewardAmount()` again, and now the full amount gets sent:
```diff
diff --git a/truflation-contracts/test/staking/VirtualStakingRewards.t.sol b/truflation-contracts/test/staking/VirtualStakingRewards.t.sol
index b2bb197..14bf9de 100644
--- a/truflation-contracts/test/staking/VirtualStakingRewards.t.sol
+++ b/truflation-contracts/test/staking/VirtualStakingRewards.t.sol
@@ -182,6 +182,45 @@ contract VirtualStakingRewardsTest is Test {
         );
     }
 
+    function testNotifyNoStakers() external {
+        console.log("Test notify with no stakers");
+
+        uint256 rewardAmount = 100_000e18;
+        uint256 aliceAmount = rewardAmount;
+
+        _notifyReward(rewardAmount);
+        vm.warp(block.timestamp + 3 days);
+        _stake(alice, aliceAmount);
+        vm.warp(block.timestamp + 4 days + 1);
+
+        assertEq(
+            trufStakingRewards.earned(alice),
+            rewardAmount,
+            "Earned amount is invalid"
+        );
+
+        // admin rescues remaining funds
+        uint256 remaining = trufToken.balanceOf(address(trufStakingRewards)) -
+            trufStakingRewards.earned(alice);
+        vm.prank(rewardsDistribuion);
+        trufStakingRewards.notifyRewardAmount(remaining);
+        vm.warp(block.timestamp + 7 days);
+        assertEq(
+            trufStakingRewards.earned(alice),
+            rewardAmount,
+            "Earned amount is invalid"
+        );
+        /**
+         [FAIL. Reason: assertion failed] testNotifyNoStakers() (gas: 248615)
+            ...
+            Left: 57142857142857142500000
+           Right: 100000000000000000000000
+            ...
+            Left: 99999999999999999400000
+           Right: 100000000000000000000000
+         */
+    }
+
     function testGetRewardForDuration() external {
         console.log("Get reward for duration");
 
```

In reality, Alice would have to re-stake after 7 days.

## Code Snippet

When `notifyRewardAmount()` is called, the full duration of the emission is set, even if there are currently no stakers:
```solidity
// File: src/staking/VirtualStakingRewards.sol : VirtualStakingRewards.notifyRewardAmount()   #1

162 @>         lastUpdateTime = block.timestamp;
163:@>         periodFinish = block.timestamp + rewardsDuration;
```
https://github.com/sherlock-audit/2023-12-truflation/blob/main/truflation-contracts/src/staking/VirtualStakingRewards.sol#L162-L163

## Tool used

Manual Review

## Recommendation

As you can see in the POC's output, there is a rounding issue leading to not all rewards being dispersed (dust amounts). Rather than trying to fix the complicated distribution logic, allow the admin to withdraw any excess funds in the contract, so that they can manually distribute them to the right participants.

Another option is to make `notifyRewardAmount()` revert if there are currently no stakers.

**Comment by detectiveking123** [comment]
Escalate

This issue doesn't have any impact. The rewards are not actually lost by anyone; as the issue states the admin can simply use the left over balance towards the next cycle. Even if there is no next cycle for whatever reason (admin wants to withdraw), admin can just stake 1 unit of TRUF themselves and withdraw the rewards over the next week (which is how long it would have taken to distribute them anyways...). 

The issue also states this:

`
The funds are not locked in the contract forever though, because the admin can call notifyRewardAmount() without transferring any extra funds, which will use the latent balance as the reward source.
`

Though I disagree when the issue says:

`However, the set of people and their durations will not be the same as the set in existence when the first notification happened.`

When there are no stakers, it's not obvious to me that anyone should be getting the staking rewards in the first place, based on the design, so this seems like correct implementation. If there's a week staking period, but Alice only stakes for 1 minute of it and there were no stakers for the rest, then she shouldn't get all the staking rewards for that week.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This issue doesn't have any impact. The rewards are not actually lost by anyone; as the issue states the admin can simply use the left over balance towards the next cycle. Even if there is no next cycle for whatever reason (admin wants to withdraw), admin can just stake 1 unit of TRUF themselves and withdraw the rewards over the next week (which is how long it would have taken to distribute them anyways...). 
> 
> The issue also states this:
> 
> `
> The funds are not locked in the contract forever though, because the admin can call notifyRewardAmount() without transferring any extra funds, which will use the latent balance as the reward source.
> `
> 
> Though I disagree when the issue says:
> 
> `However, the set of people and their durations will not be the same as the set in existence when the first notification happened.`
> 
> When there are no stakers, it's not obvious to me that anyone should be getting the staking rewards in the first place, based on the design, so this seems like correct implementation. If there's a week staking period, but Alice only stakes for 1 minute of it and there were no stakers for the rest, then she shouldn't get all the staking rewards for that week. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by IllIllI000** [comment]
Re: `simply use the left over balance towards the next cycle` as I stated in the original submission, `the set of people and their durations will not be the same as the set in existence when the first notification happened`. The design of the system is to distribute _all_ of the rewards to the people who have _locked_ during _that_ period, not to hope that the same people stuck around, and nobody else joined, for the next period. The issue has been [awarded](https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/387) in the past

**Comment by ryuheimat** [comment]
We won't fix this issue, since this issue is not critical, and non-distributed tokens could be re-distributed in next cycle.

**Comment by detectiveking123** [comment]
"The design of the system is to distribute all of the rewards to the people who have locked during that period, not to hope that the same people stuck around, and nobody else joined, for the next period."

Can you justify this is the intended design of the system... it doesn't make much sense to me. I don't think someone who locks in for a second during a one week period should be rewarded all the rewards for the entire period, even if they were the only staker. As sponsor said just distributing awards in the next period is fine (and better design in my opinion). 

I am not sure about the specific design of that Tokemak system, but I believe the issue you linked is fundamentally different in that the rewards are lost forever

**Comment by Czar102** [comment]
I agree with the escalation. The report is low/informational.

**Comment by IllIllI000** [comment]
@Czar102 can you clarify the specific difference that makes this a low as compared to the referenced prior bug? Are you saying that a project has to explicitly say in their readme that all funds need to be dispersed in order for this to be a medium, and that any ability to repurpose funds whatsoever means it's low?

**Comment by Czar102** [comment]
I think this is a valid design of the protocol, and the impact is minimal. Who loses funds?

**Comment by IllIllI000** [comment]
as was discussed [here](https://discord.com/channels/812037309376495636/1192483776622759956/1197277746364174397) it is a well-known bug of forks of this contract, so I'm just trying to understand the rules about when to submit it or not, so I don't lose points unnecessarily. I would think that a sponsor unfamiliar with this bug would want to know about this case, but if your stance is that some portion of the funds can be repurposed (the admin may want to claw back _all_ of the unused funds for themselves, but since the only way is to start a new rewards period, someone else may lock during that period, and be able to claim most of the funds), then I can accept that - just trying to understand the logic. Any portion of funds being reclaimable means low?

**Comment by Czar102** [comment]
It's not a valid finding because it is a valid design of the protocol. A design is not a security vulnerability.

**Comment by PlamenTSV** [comment]
It's not intended design, they did not know about this issue when forking the protocol (even though it is well known). And by the logic of the contract and the vulnerability itself, these funds can never be redistributed, because the first stake would always be after the new notify call, thus the funds between those 2 timestamps could never get distributed

**Comment by detectiveking123** [comment]
You are incorrect, I would recommend you to reread the code.

**Comment by Czar102** [comment]
> It's not intended design, they did not know about this issue when forking the protocol

Unless there is a signal that this wasn't expected in the README/docs, then it doesn't matter.

> these funds can never be redistributed, because the first stake would always be after the new notify call, thus the funds between those 2 timestamps could never get distributed

@PlamenTSV this was contested so would appreciate more context on this statement.

**Comment by PlamenTSV** [comment]
The core of the vulnerability is the fact that rewards for the period between the call to ``notifyRewards`` and the first stake would be lost. The counterargument is that these funds are inside the contract so they can be redistributed by calling ``notifyRewards`` again, but I reckon this would circle back to the beginning, since now you would still have an X amount of time between the new ``notifyRewards`` call and the next stake. And for that X amount the rewards are not distributed.
@IllIllI000 talks about the dust amounts affecting the calculation and the initial escalation is that admins can just rescue these funds, but aren't the rewards the user was supposed to get, but DID NOT count as a loss of funds for the user?
In my #23 I provide a link to an already live practical mitigation

**Comment by detectiveking123** [comment]
That doesn't make sense. If there is no one staking, you wouldn't want to distribute in the current round anyways.

**Comment by 0xunforgiven** [comment]
just want to add the supply==0 case doesn't happen only when notify is called, it can happen in the middle of the reward distribution if all the stackers unstack their tokens then supply==0 and contract would stop distributing the rewards.
so adding a check for starting the rewards distribution doesn't mitigate the supply==0 case.

the important point is that rare case is handled by current implementation. in any time, if no one is stacking(supply==0) then the correct thing to do(which is by design) is not distribute rewards(there is no one to receive those rewards) and keep those rewards in the contract. those unused rewards can be recycled in the next cycles. This is the intended design of the system. the intended behavior is reward distribution per seconds between stackers.

in the original code it wasn't possible to recycle the unused rewards so this was an issue(remained rewards were lost), but in this code, unused reward can be recycled.

PlamenTSV logic is that even if admin recycle the unused rewards, in each next cycle when calling notify, pool is empty and again supply==0 case will happen and again some dust rewards will remain and this will keep happening. this is a big assumption that assume that rare case(no stackers, supply==0) gonna happen "every time" before notify call:
1. every time that admin calls notify, users are already unstacked their tokens and supply==0.
2. every time admin is gonna wait for pool to be empty to call notify again.

but in reality users have incentive to stake and keep their stake and admin can call notify any time he wants. admin doesn't gonna wait for pool to be empty to call notify. design of the system allows admin to call notify anytime he wants even in middle of the current reward distribution.

**Comment by Czar102** [comment]
Result:
Invalid
Has duplicates

Considering this a design choice based on the above discussion.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [detectiveking123](https://github.com/sherlock-audit/2023-12-truflation-judging/issues/126/#issuecomment-1897836860): accepted
