### ISSUE TITLE
phenom - Potential Contract Drain Vulnerability via Insecure Leaf Calculation in TrufMigrator's Merkle Proof Mechanism

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2023-12-truflation-judging#181]
phenom

high

# Potential Contract Drain Vulnerability via Insecure Leaf Calculation in TrufMigrator's Merkle Proof Mechanism

## Summary
The contract `TrufMigrator` uses a Merkle tree for token migration, but the method used to calculate the leaf node in the Merkle tree might lead to vulnerabilities if `msg.sender` contains a high value, potentially allowing the contract balance to be drained.

## Vulnerability Detail
The vulnerability arises from the method of generating the leaf node for Merkle proof verification. The leaf is calculated using `keccak256(abi.encode(msg.sender, index, amount))`. As `msg.sender` is an address (which is a `uint256` type), it could potentially hold a high value. If this value is greater than the `amount` being claimed, it could lead to a situation where an attacker can generate a valid proof for an amount higher than what they are eligible for, potentially draining the contract balance.

## Impact
The impact of this vulnerability could result in the draining of the contract's token balance if an attacker manipulates the `msg.sender` value to generate a proof for a higher amount than their entitlement.

## Code Snippet
https://github.com/sherlock-audit/2023-12-truflation/blob/37ddbb69e0c7fb6510f1ec99162fd9172ec44733/truflation-contracts/src/token/TrufMigrator.sol#L49
```solidity
// Code snippet showing vulnerable leaf calculation
bytes32 leaf = keccak256(abi.encode(msg.sender, index, amount));
```

## Tool used

Manual Review

## Recommendation
It's recommended to review the leaf calculation method and find a deterministic approach that ensures the token amount is correctly calculated and prevents potential abuse from high msg.sender values. Consider using a different combination of values or a more secure method to create the leaf node, ensuring that the claimed amount aligns accurately with the proof provided.

Duplicate of #36

**Comment by ryuheimat** [comment]
Need more details

**Comment by MR-Abbasnejad** [comment]
> Need more details

The vulnerability here lies in the limitation of the migrate() function. Currently, it's restricted to be called only by the address intending to migrate its tokens. The issue arises because contracts that own TFI tokens and are part of the merkle tree may not have any built-in logic to call the migrate() function, resulting in the loss of their TFI tokens and the inability to receive new TRUF tokens.

The migrate() function, as it stands, requires the caller to be the owner of the tokens. However, in scenarios involving contracts owning tokens, there's no guarantee these contracts possess the necessary logic to trigger the migrate() function on their own.

To address this problem, the contract should allow anyone to call the migrate() function for any address. Currently, there's no risk associated with others calling migrate() for different addresses, and enabling this functionality would ensure that contract owners can trigger the migration for their contracts, preventing the loss of their TFI tokens and allowing them to receive the new TRUF tokens.

Combining both vulnerabilities, the contract should:

Revisit the leaf calculation method to prevent potential abuse due to high msg.sender values.
Modify the migrate() function to allow anyone to call it for any address, ensuring contracts that own tokens can trigger the migration process themselves.
By making these adjustments, the contract will enhance its security while ensuring that all token holders, including contracts, can seamlessly migrate their tokens to receive the new TRUF tokens without the risk of losing their tokens due to lack of migration logic.

**Comment by ryuheimat** [comment]
Sorry, I think this is not necessary functionality.
We intended for users to migrate themselves
