### ISSUE TITLE
bughuntoor - `claimable` prior to cliff does not account for the emission left, leading to overdistribution

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-truflation-judging#32]
bughuntoor

high

# `claimable` prior to cliff does not account for the emission left, leading to overdistribution

## Summary
`claimable` prior to cliff does not account for the emission left, leading to overdistribution

## Vulnerability Detail
After a user's vesting begins, up until the `cliff` timestamp, the user can claim their `initialRelease`. However, in the current implementation when the user claims their 'initialRelease` it does not take into consideration the current emission left. 
```solidity
        uint256 totalAmount = userVesting.amount;

        uint256 initialRelease = (totalAmount * info.initialReleasePct) / DENOMINATOR;

        startTime += info.cliff;

        if (startTime > block.timestamp) {
            return initialRelease;
        }
```
Since it does not account for the emission left, this allows overdistribution of funds. Furthermore, after this overdistribution happens, it would cause subsequent calls to `claimable` to revert due to underflow in the #L197 (`totalClaimed > getEmission(categoryId)`)
```solidity
        uint256 emissionLeft = getEmission(categoryId) - categories[categoryId].totalClaimed;
```

Marking this as High, as not only it causes overdistribution, but it also breaks an invariant, causing claimable to unexpectedly revert.

## Impact
Overdistribution of vesting amounts.
`claimable` unexpectedly reverting.

## Code Snippet
https://github.com/sherlock-audit/2023-12-truflation/blob/main/truflation-contracts/src/token/TrufVesting.sol#L174C1-L178C33

## Tool used

Manual Review

## Recommendation
When returning the `initialRelease` check it against the current `emissionLeft`

Duplicate of #1

**Comment by deadrosesxyz** [comment]
Escalate
Valid issue, there could be overdistribution + DoS. ANY admin configuration can be broken and result into overdistribution + DoS (not only a specific one, as commented by judge)

**Comment by nevillehuang** [comment]
@deadrosesxyz could you provide a scenario/PoC that this will underflow? To my knowledge emissions are scheduled by the admin and truncated accordingly [here](https://github.com/sherlock-audit/2023-12-truflation/blob/main/truflation-contracts/src/token/TrufVesting.sol#L200)

Are you saying a user can claim multiple times similar to #1, so emissions are also assigned to users multiple times? 

@ryuheimat you might want to take a look

**Comment by ryuheimat** [comment]
@nevillehuang This is similar with https://github.com/sherlock-audit/2023-12-truflation-judging/issues/7
There are three things we need to consider - `claimed`, `locked`, and `emission left`
Now there are 3 separate issues that we didn't consider each ones.

These both 3 issues can be fixed in single PR i attached at https://github.com/sherlock-audit/2023-12-truflation-judging/issues/1

**Comment by deadrosesxyz** [comment]
Scenario
 - Emission is fully claimed up thus far
 - A user who has just received their vest claims their initialAmount (`totalClaimed > emission` now)
 - next call to claimable reverts on #L197 due to         `getEmission(categoryId) - categories[categoryId].totalClaimed`; (as I’ve described why `totalClaimed > emission`)

**Comment by nevillehuang** [comment]
Ok @ryuheimat so via the fix in#1, as long as user cannot claim multiple times the initialRelease than  this is a non issue right?

if thats the case I think this would be a duplicate of #1 given same root cause

**Comment by ryuheimat** [comment]
That's right

**Comment by ryuheimat** [comment]
https://github.com/sherlock-audit/2023-12-truflation-judging/issues/1 issue title is that users are able to drain whole tokens from vesting contract, however they just mentioned about non `claimed` amount check here.
Actually, `locked` and `emission left` non-validation is draining factor.
So i think it's reasonable to mark as duplicated

**Comment by deadrosesxyz** [comment]
The fix which fixed multiple claims was different. It required checking against claimed amount. If you check for claimed amount, this issue remains, hence, they are 2 different issues.

> These both 3 issues can be fixed in single PR i attached at https://github.com/sherlock-audit/2023-12-truflation-judging/issues/1


As states by the dev, they are 3 different issues. Fixing them in the same PR does not combine them into 1 issue.

**Comment by ryuheimat** [comment]
@deadrosesxyz https://github.com/sherlock-audit/2023-12-truflation-judging/issues/1 mentioned that vesting contract could be drained.
The reason is that we just return `initialReleaseAmount` if timestamp is before cliff.
Not considering `claimed`, Not considering `locked`, Not considering `emission left` are same as we just returning `initialReleaseAmount`

**Comment by sherlock-admin2** [comment]
> Escalate
> Valid issue, there could be overdistribution + DoS. ANY admin configuration can be broken and result into overdistribution + DoS (not only a specific one, as commented by judge)

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by 0xunforgiven** [comment]
summery of scalations regarding #1 duplicates, ([comment1](https://github.com/sherlock-audit/2023-12-truflation-judging/issues/2#issuecomment-1894840619) [comment2](https://github.com/sherlock-audit/2023-12-truflation-judging/issues/32#issuecomment-1894837551))

there are 3 bug in the `claimable()` function for `initialRelease`:
1. code doesn't subtract the `claimed` from `initialRelease`. 
(impact: one user can drain the contract. also one user can bypass vesting schedule)

2. code doesn't make sure that `initialRelease` is lower than `maxClaimable = userVesting.amount - userVesting.locked`.
(impact: one user can claim his `intialRelease` while he locked all his tokens)

3. code doesn't make sure that `initialRelease` is less than emission left.
(impact: user can bypass emission policy)

These 3 issue have different root cause, impacts, attack vector, fix and severity. the only thing common between them is that they happen in the same function for same execution flow. 

Fixing one these bugs doesn't fix the others completely(as mentioned in this [comment](https://github.com/sherlock-audit/2023-12-truflation-judging/issues/32#issuecomment-1894867768) and duplicate issues POCs). the answer to the below  question that lead judge mentioned in this [comment](https://github.com/sherlock-audit/2023-12-truflation-judging/issues/32#issuecomment-1894868465) is No. (fixing bug 1 doesn't fix bug 2 or bug 3 and vice versa)
> as long as user cannot claim multiple times the initialRelease than this is a non issue right?

Also as lead judge [mentioned](https://github.com/sherlock-audit/2023-12-truflation-judging/issues/2#issuecomment-1895011693)  some wardens reports these issues in one report and some wardens reported them separately.

the fixed code should be like:
```javascript
        if (startTime > block.timestamp) {
            // @audit fix for bug #1
            uint256 maxClaimable = userVesting.amount - userVesting.locked;
            if (initialRelease  > maxClaimable) {
                initialRelease  = maxClaimable;
            }

            // @audit fix for bug #2
            if (initialRelease > userVesting.claimed) {
                initialRelease = initialRelease - userVesting.claimed;
            }else {
                initialRelease = 0;
            }
            
            // @audit fix for bug #3
            if (initialRelease  > emissionLeft) {
                     initialRelease  = emissionLeft;
            }
            
            return initialRelease ;
     }
```

**Comment by ryuheimat** [comment]
https://github.com/truflation/truflation-contracts/pull/3

This PR was made to fix https://github.com/sherlock-audit/2023-12-truflation-judging/issues/1 and this fixes this issue as well.
https://github.com/sherlock-audit/2023-12-truflation-judging/issues/1 and this issue have similarity, we used other solution to fix both in better way.

**Comment by mstpr** [comment]
Fix LGTM

**Comment by Czar102** [comment]
After looking deep into the issues, I think these are duplicates, especially given that the sponsor's fix fixes all issues. Returning the value early was the single issue, which causes many different things to break, including lack of validation of values implemented later in the function.

Hence, planning to reject the escalation and leave the issues as they are.

**Comment by Czar102** [comment]
Sorry, I meant – this should be a valid duplicate of #1. Duplicates of #1 won't be deduplicated. Will accept the escalation.

**Comment by Czar102** [comment]
Result:
High
Duplicate of #1

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [deadrosesxyz](https://github.com/sherlock-audit/2023-12-truflation-judging/issues/32/#issuecomment-1894837551): accepted
